import { useEffect, useMemo, useState, type ReactNode } from 'react';
import {
  ArrowUpRight, Check, ChevronDown, ChevronRight, Clipboard, Copy, ExternalLink,
  Menu, Search, ShieldCheck, WalletCards, X,
} from 'lucide-react';
import { docsTopics, searchDocs } from './docsSearch';

const RPC = 'https://rpc.mainnet.chain.robinhood.com';
const EXPLORER = 'https://robinhoodchain.blockscout.com';
const USDG = '0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168';
const QUOTER = '0x33e885ed0ec9bf04ecfb19341582aadcb4c8a9e7';
const ROUTER = '0xcaf681a66d020601342297493863e78c959e5cb2';
const FACTORY = '0x1f7d7550b1b028f7571e69a784071f0205fd2efa';
const CCIP_ROUTER = '0x06fC836cf9839B1cd891C440A0a45242DA6Ae1c9';

function CopyValue({ value }: { value: string }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    await navigator.clipboard.writeText(value);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1400);
  };
  return <button className="docs-copy" onClick={() => void copy()} aria-label={`Copy ${value}`}>{copied ? <Check size={14} /> : <Copy size={14} />}<span>{copied ? 'Copied' : 'Copy'}</span></button>;
}

function CodeLine({ label, value, link }: { label: string; value: string; link?: string }) {
  return <div className="docs-code-line"><span>{label}</span><code>{value}</code>{link ? <a href={link} target="_blank" rel="noreferrer" aria-label={`Open ${label}`}><ExternalLink size={14} /></a> : <CopyValue value={value} />}</div>;
}

function Callout({ children, tone = 'blue' }: { children: ReactNode; tone?: 'blue' | 'amber' }) {
  return <aside className={`docs-callout ${tone}`}><ShieldCheck size={17} /><div>{children}</div></aside>;
}

function Section({ id, eyebrow, title, children }: { id: string; eyebrow: string; title: string; children: ReactNode }) {
  return <section className="docs-section" id={id}><p className="docs-eyebrow">{eyebrow}</p><h2>{title}</h2>{children}</section>;
}

export default function DocsPage() {
  const [query, setQuery] = useState('');
  const [mobileNav, setMobileNav] = useState(false);
  const [active, setActive] = useState('overview');
  const filtered = useMemo(() => searchDocs(query), [query]);

  useEffect(() => {
    document.title = 'QUEN documentation';
    const meta = document.querySelector('meta[name="description"]');
    if (meta) meta.setAttribute('content', 'Production documentation for QUEN verified execution on Robinhood Chain.');
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActive(entry.target.id)), { rootMargin: '-18% 0px -70% 0px' });
    docsTopics.forEach(({ id }) => { const node = document.getElementById(id); if (node) observer.observe(node); });
    return () => observer.disconnect();
  }, []);

  return <div className="docs-page">
    <header className="docs-header"><a href="/" className="docs-brand"><img src="/quen-logo-blue.png" alt="QUEN" /><span>QUEN <small>DOCUMENTATION</small></span></a><div className="docs-header-actions"><a href="/app">Open console <ArrowUpRight size={15} /></a><button className="docs-mobile-toggle" onClick={() => setMobileNav(!mobileNav)} aria-label="Toggle documentation navigation">{mobileNav ? <X /> : <Menu />}</button></div></header>
    <div className="docs-layout">
      <aside className={`docs-sidebar ${mobileNav ? 'open' : ''}`}><div className="docs-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search docs" aria-label="Search docs" /></div><nav>{filtered.map((topic) => <a key={topic.id} href={`#${topic.id}`} className={active === topic.id ? 'active' : ''} onClick={() => setMobileNav(false)}>{topic.title}<ChevronRight size={13} /></a>)}</nav><div className="docs-side-note"><WalletCards size={15} /><span>Non-custodial by design.<br />You sign every transaction.</span></div></aside>
      <main className="docs-main">
        <section className="docs-hero" id="overview"><div><p className="docs-kicker">QUEN / PRODUCTION DOCS</p><h1>Verified execution<br /><em>for tokenized markets.</em></h1><p className="docs-lede">QUEN is an execution layer for tokenized markets on Robinhood Chain. It reads the chain, qualifies a route, and keeps the wallet in control of every signature.</p><div className="docs-hero-actions"><a className="docs-primary" href="#quick-start">Start here <ChevronRight size={16} /></a><a className="docs-secondary" href={EXPLORER} target="_blank" rel="noreferrer">Open Blockscout <ExternalLink size={14} /></a></div></div><div className="docs-hero-mark"><span>4663</span><small>ROBINHOOD CHAIN<br />MAINNET</small></div></section>
        <Callout>Live surfaces are intentionally narrow: RWA Gateway, Settlement Rails, and only Unified Liquidity routes that pass current verification. A route marked unavailable is not a simulation.</Callout>
        <Section id="quick-start" eyebrow="01 / FIRST RUN" title="Quick start"><p>Use the product in four deliberate steps. Nothing moves until the route and your wallet state agree.</p><div className="docs-steps">{[['01','Set the network','Add Robinhood Chain using the values below. Keep ETH available for gas.'],['02','Connect a wallet','Connect an EIP-1193 wallet. QUEN reads public state; your wallet keeps the keys.'],['03','Choose a surface','Open RWA Gateway to trade, Settlement Rails to send or request USDG, or Unified Liquidity to review qualified routes.'],['04','Review, then sign','Inspect the destination, amount, quote and checks. Sign in your wallet only when the review matches your intent.']].map(([n, t, d]) => <div className="docs-step" key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></div>)}</div></Section>
        <Section id="network" eyebrow="02 / NETWORK" title="Network setup"><p>All current QUEN surfaces target Robinhood Chain mainnet. Copy these values into your wallet or developer tooling.</p><div className="docs-code-card"><CodeLine label="NETWORK" value="Robinhood Chain" /><CodeLine label="CHAIN ID" value="4663  ·  0x1237" /><CodeLine label="NATIVE GAS" value="ETH" /><CodeLine label="PUBLIC RPC" value={RPC} /><CodeLine label="EXPLORER" value={EXPLORER} link={EXPLORER} /><CodeLine label="USDG" value={`${USDG}  ·  6 decimals`} /></div><p className="docs-inline-link"><a href={EXPLORER} target="_blank" rel="noreferrer">Verify the network on Blockscout <ExternalLink size={14} /></a></p></Section>
        <Section id="product-map" eyebrow="03 / SURFACES" title="One network, three jobs"><div className="docs-product-map"><a href="/app/rwa"><span>RWA GATEWAY</span><h3>Trade canonical Robinhood Tokens against USDG.</h3><p>Every market is assessed before a quote or transaction can proceed.</p><ArrowUpRight /></a><a href="/app/settlement"><span>SETTLEMENT RAILS</span><h3>Send USDG or make an EIP-681 payment request.</h3><p>Single-chain transfer review, simulation and receipt verification.</p><ArrowUpRight /></a><a href="/app"><span>UNIFIED LIQUIDITY</span><h3>Review only routes that pass live qualification.</h3><p>Blocked routes stay unavailable instead of pretending to be executable.</p><ArrowUpRight /></a></div></Section>
        <Section id="rwa-gateway" eyebrow="04 / RWA GATEWAY" title="Trade only when the route is qualified"><p>RWA Gateway trades canonical Robinhood Tokens against canonical USDG. A registry entry alone does not make an asset tradable.</p><div className="docs-two-col"><div><h3>BUY / SELL flow</h3><ol className="docs-list"><li>Select an asset and direction: BUY uses USDG in; SELL uses the token in.</li><li>Wait for market assessment: registry identity, contract controls, venue and pool checks are read from the chain.</li><li>Enter an amount. The quoter returns a short-lived quote and the app performs a reverse quote to measure round-trip loss.</li><li>Review allowance, balance, minimum output, deadline and simulation results.</li><li>Approve only when needed, then sign the swap. Wait for the receipt and verify it in the explorer.</li></ol></div><div><h3>What can block a trade?</h3><ul className="docs-check-list"><li>Unverified token metadata or bytecode</li><li>Paused transfer or oracle controls</li><li>Missing or unhealthy USDG pool</li><li>Venue, fee tier, TWAP or quote checks failing</li><li>Insufficient balance, allowance or gas</li><li>Stale quote, failed simulation or wallet mismatch</li></ul></div></div><div className="docs-status-row"><span>REGISTRY</span><span>QUALIFIED</span><span>TRADABLE</span><span>BLOCKED</span></div><p className="docs-muted">Statuses describe evidence available now. Chainlink tokenized-equity feeds, where mapped, are reference prices—not DEX execution prices—and are not available for every asset. There is no QUEN-specific KYC or jurisdiction gate.</p></Section>
        <Section id="settlement" eyebrow="05 / SETTLEMENT RAILS" title="Move USDG with clear confirmation semantics"><p>Settlement Rails currently supports real single-chain USDG transfers on Robinhood Chain and EIP-681 payment requests.</p><div className="docs-two-col"><div><h3>Send</h3><ol className="docs-list"><li>Connect on Robinhood Chain and enter a recipient plus USDG amount.</li><li>Review balance, token state, gas estimate and recipient.</li><li>QUEN rechecks chain, balance, token status and transfer simulation immediately before signing.</li><li>After submission, it waits for one confirmation and verifies the USDG <code>Transfer</code> event.</li></ol></div><div><h3>Receive / request</h3><ol className="docs-list"><li>Choose Receive / Request and enter an amount.</li><li>Copy the generated EIP-681 URI or share it with the payer.</li><li>The URI is a payment request, not an on-chain transaction until a wallet pays it.</li></ol></div></div><Callout tone="amber">Settlement is single-chain USDG. Do not interpret the payment request as cross-chain support.</Callout></Section>
        <Section id="liquidity" eyebrow="06 / UNIFIED LIQUIDITY" title="Qualification before capital"><p>Unified Liquidity presents the network-wide surface, but only verified routes are actionable. A route may show as <strong>Live</strong>, <strong>Qualified</strong>, <strong>Blocked</strong>, or <strong>Unavailable</strong>.</p><div className="docs-route-diagram"><span>source asset</span><ChevronRight /><span>identity + permission checks</span><ChevronRight /><span>balance + simulation</span><ChevronRight /><span className="live">actionable route</span></div><p>For the live USDG route, source data is checked against the configured vault and current indexed data. Approval, deposit and withdrawal actions are revalidated and simulated immediately before wallet submission. No route promises yield, APY, safety or redemption unless that behavior is proven live.</p><a className="docs-text-link" href="/app">Open Unified Liquidity <ArrowUpRight size={14} /></a></Section>
        <Section id="wallet" eyebrow="07 / WALLET" title="The wallet owns the lifecycle"><div className="docs-lifecycle">{['Read public network state','Connect account','Review fresh checks','Sign in wallet','Wait for receipt','Verify on Blockscout'].map((item, i) => <div key={item}><b>0{i + 1}</b><span>{item}</span></div>)}</div><p>QUEN does not hold private keys or custody assets. Your wallet signs transactions. Allowances are requested only where the contract flow needs them, and a receipt is not treated as success until the expected result is verified.</p></Section>
        <Section id="data" eyebrow="08 / EVIDENCE" title="Data sources and price model"><div className="docs-table-wrap"><table><thead><tr><th>Source</th><th>Used for</th><th>Important boundary</th></tr></thead><tbody><tr><td>Robinhood Chain RPC</td><td>Contract reads, balances, blocks, simulations</td><td>Network state can be temporarily unavailable.</td></tr><tr><td>DEX pools and quoter</td><td>Executable quotes, spot and TWAP checks</td><td>Execution price can differ from reference feeds.</td></tr><tr><td>Chainlink mappings</td><td>Reference tokenized-equity prices where mapped</td><td>Not a DEX price; not every asset has a mapping.</td></tr><tr><td>Blockscout</td><td>Independent receipt and event inspection</td><td>Use the transaction hash, not a UI label alone.</td></tr></tbody></table></div></Section>
        <Section id="safety" eyebrow="09 / VERIFICATION" title="Safety is a gate, not a badge"><p>Before funds can move, QUEN checks the specific action against current chain evidence: canonical identity, deployed bytecode, metadata, transfer and oracle controls, authority storage, execution venue, fee pools, liquidity, TWAP, quote freshness, round-trip loss, balance, allowance, gas and simulation.</p><div className="docs-pills">{['Canonical identity','Contract controls','Pool health','Fresh quote','Round-trip check','Wallet state','Simulation','Receipt event'].map((item) => <span key={item}><Check size={13} />{item}</span>)}</div><p className="docs-muted">A passing check is a point-in-time observation. It is not a guarantee about future liquidity, issuer behavior, network reliability or market outcomes.</p></Section>
        <Section id="contracts" eyebrow="10 / REFERENCES" title="Verified contract references"><p>These addresses are sourced from the current application code and used as runtime references on chain.</p><div className="docs-address-table">{[['Canonical USDG','Token','6 decimals',USDG],['RWA quoter','Execution quote contract','RWA Gateway',QUOTER],['RWA router','Execution router','RWA Gateway',ROUTER],['RWA factory','Pool discovery','RWA Gateway',FACTORY],['Chainlink CCIP router','Infrastructure reference only','Not proof of USDG cross-chain support',CCIP_ROUTER]].map(([name, role, note, address]) => <div key={name}><strong>{name}</strong><span>{role}<small>{note}</small></span><code>{address}</code><CopyValue value={address} /></div>)}</div></Section>
        <Section id="troubleshooting" eyebrow="11 / RECOVERY" title="Troubleshooting"><div className="docs-faq"><details><summary>Why is an asset Registry or Blocked? <ChevronDown /></summary><p>Registry means the asset is known but the live evidence is incomplete. Blocked means one or more required checks failed. Neither status implies a trade is available.</p></details><details><summary>My wallet is on the wrong network <ChevronDown /></summary><p>Switch to chain 4663 (0x1237), then reconnect or refresh the surface. Keep ETH on that network for gas.</p></details><details><summary>A quote expired <ChevronDown /></summary><p>Quotes are intentionally short-lived. Re-enter or refresh the amount to request a new quote; never rely on a stale output.</p></details><details><summary>The transaction says submitted but not confirmed <ChevronDown /></summary><p>Open the hash in Blockscout and check the receipt and expected event before attempting another transaction.</p></details></div></Section>
        <Section id="faq" eyebrow="12 / FAQ" title="Frequently asked questions"><div className="docs-faq"><details><summary>Does QUEN custody my funds? <ChevronDown /></summary><p>No. QUEN does not hold keys. Your connected wallet signs the transaction and the contracts execute on chain.</p></details><details><summary>Can I trade every registry asset? <ChevronDown /></summary><p>No. A registry listing is not a tradability promise. The market must pass the live token, venue, pool, quote and wallet checks.</p></details><details><summary>Are reference feeds execution prices? <ChevronDown /></summary><p>No. They are reference prices for mapped assets. The executable price comes from the verified DEX route.</p></details><details><summary>Does Settlement Rails bridge USDG? <ChevronDown /></summary><p>No. It currently sends USDG on Robinhood Chain and creates single-chain EIP-681 payment requests.</p></details></div></Section>
        <Section id="risks" eyebrow="13 / DISCLOSURES" title="Read this before using the products"><div className="docs-risk"><p>Tokenized equities are economic exposure, not direct ownership of the underlying shares. DEX execution can differ from reference feeds and may include slippage, fees and price impact.</p><p>Smart-contract, liquidity, oracle, issuer, administrator and network risks can cause loss, delay, interruption or a different outcome than expected. A verified route is not a guarantee of safety, liquidity, yield, APY, redemption or future availability.</p><p>QUEN documentation is informational only and is not investment, legal or tax advice. Review the relevant issuer and protocol materials for your own circumstances.</p></div></Section>
        <footer className="docs-footer"><span>QUEN / VERIFIED EXECUTION LAYER</span><div><a href="/app/rwa">RWA Gateway</a><a href="/app/settlement">Settlement Rails</a><a href="/app">Unified Liquidity</a><a href="https://x.com/QuenOfc" target="_blank" rel="noreferrer">X / @QuenOfc <ExternalLink size={13} /></a><a href={EXPLORER} target="_blank" rel="noreferrer">Blockscout <ExternalLink size={13} /></a></div></footer>
      </main>
    </div>
  </div>;
}